name = "Sundial"
version = "1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f1603e979e271a6efdeecde268ecba25d9c5995c455137d02ee07a665619bb12"

[versions]
forge = "40.2.1"
minecraft = "1.18.2"
