name = "Sundial"
version = "1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e82423f1a950edefd3d164a89d9ff8a49126d6aeaded4f21243b61ab6a331490"

[versions]
forge = "40.2.1"
minecraft = "1.18.2"
