name = "Sundial"
version = "1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1dd79f93f377ac6becb54dae76e129973428b3a6c1f49e97b660f717160b3e02"

[versions]
forge = "40.2.1"
minecraft = "1.18.2"
